import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
    container: { flex: 1 },
    hero: {
        paddingHorizontal: 16,
        paddingTop: 24,
        paddingBottom: 24,
        borderBottomLeftRadius: 24,
        borderBottomRightRadius: 24,
        marginBottom: 14,
        elevation: 4,
        backgroundColor: '#0F172A', // charcoal base
        overflow: 'hidden',
        position: 'relative',
    },
    facetOne: {
        position: 'absolute',
        width: 220,
        height: 220,
        backgroundColor: '#F59E0B',
        opacity: 0.32,
        top: -80,
        left: -60,
        transform: [{ rotate: '-18deg' }],
    },
    facetTwo: {
        position: 'absolute',
        width: 260,
        height: 260,
        backgroundColor: '#D97706',
        opacity: 0.22,
        top: -30,
        right: -120,
        transform: [{ rotate: '12deg' }],
    },
    facetThree: {
        position: 'absolute',
        width: 240,
        height: 240,
        backgroundColor: '#B45309',
        opacity: 0.26,
        bottom: -120,
        left: -40,
        transform: [{ rotate: '8deg' }],
    },
    heroContent: { position: 'relative' },
    heroTopRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    heroActions: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
    },
    heroKicker: { color: 'rgba(255,255,255,0.78)', fontSize: 13, marginBottom: 2 },
    heroTitle: { color: '#FFFFFF', fontSize: 26, fontWeight: '800', letterSpacing: 0.4 },
    heroSubtitleRow: { marginTop: 6 },
    heroSubtitle: { color: 'rgba(255,255,255,0.9)', fontSize: 13 },
    heroIconBtn: {
        width: 40,
        height: 40,
        borderRadius: 20,
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.5)',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: 'rgba(255,255,255,0.12)',
    },
    searchRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 16,
        gap: 10,
    },
    searchField: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        paddingHorizontal: 12,
        height: 56,
        borderRadius: 18,
        backgroundColor: '#FFFFFF',
        shadowOpacity: 0.12,
        shadowOffset: { width: 0, height: 10 },
        shadowRadius: 20,
        elevation: 3,
    },
    searchInput: {
        flex: 1,
        fontSize: 15,
        color: '#0F172A',
    },
    searchButton: {
        height: 56,
        paddingHorizontal: 18,
        borderRadius: 18,
        backgroundColor: '#1F6FEB',
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: '#1F6FEB',
        shadowOpacity: 0.25,
        shadowOffset: { width: 0, height: 10 },
        shadowRadius: 20,
        elevation: 3,
    },
    searchButtonText: {
        color: '#FFFFFF',
        fontWeight: '700',
        fontSize: 15,
    },
    section: {
        marginTop: 4,
    },
    sectionHeaderRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 16,
    },
    sectionTitle: { fontSize: 17, fontWeight: '800' },
    sectionLink: { fontSize: 14, fontWeight: '700' },
    recentCard: {
        width: 160,
        padding: 12,
        borderRadius: 12,
        borderWidth: 1,
        shadowOpacity: 0.05,
        shadowOffset: { width: 0, height: 6 },
        shadowRadius: 12,
        elevation: 1,
    },
    recentTitle: { fontSize: 15, fontWeight: '700', marginBottom: 6 },
    recentMetaRow: { flexDirection: 'row', alignItems: 'center', gap: 6 },
    recentMeta: { fontSize: 12 },
    filterRow: { flexDirection: 'row', alignItems: 'center', gap: 6 },
});

export default styles;
