import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
    container: { flex: 1 },
    hero: {
        paddingHorizontal: 20,
        paddingTop: 36,
        paddingBottom: 32,
        borderBottomLeftRadius: 28,
        borderBottomRightRadius: 28,
        marginBottom: 18,
        elevation: 6,
        backgroundColor: '#1DA1F2',
        overflow: 'hidden',
        position: 'relative',
        minHeight: 280,
    },
    facetOne: {
        position: 'absolute',
        width: 280,
        height: 280,
        backgroundColor: '#8CD6FF',
        opacity: 0.20,
        top: -110,
        left: -70,
        transform: [{ rotate: '-18deg' }],
    },
    facetTwo: {
        position: 'absolute',
        width: 320,
        height: 320,
        backgroundColor: '#5CB8F5',
        opacity: 0.18,
        top: -40,
        right: -140,
        transform: [{ rotate: '12deg' }],
    },
    facetThree: {
        position: 'absolute',
        width: 300,
        height: 300,
        backgroundColor: '#3AA6EC',
        opacity: 0.22,
        bottom: -140,
        left: -60,
        transform: [{ rotate: '8deg' }],
    },
    heroContent: { position: 'relative' },
    heroTopRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    heroActions: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
    },
    heroKicker: { color: 'rgba(255,255,255,0.78)', fontSize: 13, marginBottom: 2 },
    heroTitle: { color: '#FFFFFF', fontSize: 26, fontWeight: '800', letterSpacing: 0.4 },
    heroSubtitleRow: { marginTop: 6 },
    heroSubtitle: { color: 'rgba(255,255,255,0.9)', fontSize: 13 },
    heroIconBtn: {
        width: 40,
        height: 40,
        borderRadius: 20,
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.5)',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: 'rgba(255,255,255,0.12)',
    },
    searchRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 18,
    },
    searchField: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
        paddingHorizontal: 14,
        height: 58,
        borderRadius: 22,
        shadowOpacity: 0.14,
        shadowOffset: { width: 0, height: 12 },
        shadowRadius: 22,
        elevation: 3,
    },
    searchInput: {
        flex: 1,
        fontSize: 15,
        color: '#0F172A',
    },
    section: {
        marginTop: 4,
    },
    sectionHeaderRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 16,
    },
    sectionTitle: { fontSize: 17, fontWeight: '800' },
    sectionLink: { fontSize: 14, fontWeight: '700' },
    recentCard: {
        width: 160,
        padding: 12,
        borderRadius: 12,
        borderWidth: 1,
        shadowOpacity: 0.05,
        shadowOffset: { width: 0, height: 6 },
        shadowRadius: 12,
        elevation: 1,
    },
    recentTitle: { fontSize: 15, fontWeight: '700', marginBottom: 6 },
    recentMetaRow: { flexDirection: 'row', alignItems: 'center', gap: 6 },
    recentMeta: { fontSize: 12 },
    filterRow: { flexDirection: 'row', alignItems: 'center', gap: 6 },
    filterPanel: {
        marginHorizontal: 16,
        marginBottom: 12,
        padding: 12,
        borderWidth: 1,
        borderRadius: 14,
        shadowOpacity: 0.04,
        shadowOffset: { width: 0, height: 8 },
        shadowRadius: 14,
        elevation: 1,
        gap: 4,
    },
    filterLabel: {
        fontSize: 13,
        fontWeight: '700',
    },
    chipRow: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 8,
        marginTop: 6,
    },
    chip: {
        paddingHorizontal: 12,
        paddingVertical: 8,
        borderRadius: 12,
        borderWidth: 1,
    },
    chipActive: {
        shadowOpacity: 0.06,
        shadowOffset: { width: 0, height: 6 },
        shadowRadius: 12,
        elevation: 1,
    },
    chipText: {
        fontSize: 13,
        fontWeight: '700',
    },
});

export default styles;
