import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
    container: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        overflow: 'hidden',
    },
    content: {
        alignItems: 'center',
        paddingHorizontal: 32,
        gap: 10,
    },
    brand: {
        marginTop: 18,
        fontSize: 32,
        fontWeight: '900',
        letterSpacing: 1.2,
        color: '#FFFFFF',
        textTransform: 'uppercase',
    },
    subtitle: {
        marginTop: 4,
        fontSize: 15,
        color: 'rgba(255,255,255,0.94)',
        textAlign: 'center',
        lineHeight: 22,
    },
    tagline: {
        fontSize: 13,
        color: 'rgba(255,255,255,0.85)',
        letterSpacing: 0.6,
    },
    facetOne: {
        position: 'absolute',
        width: 360,
        height: 360,
        top: -140,
        left: -120,
        borderRadius: 180,
        opacity: 0.28,
        transform: [{ rotate: '-14deg' }],
    },
    facetTwo: {
        position: 'absolute',
        width: 280,
        height: 280,
        bottom: 90,
        right: -90,
        borderRadius: 160,
        opacity: 0.18,
        transform: [{ rotate: '18deg' }],
    },
    facetThree: {
        position: 'absolute',
        width: 320,
        height: 320,
        top: 80,
        right: -120,
        borderRadius: 160,
        opacity: 0.20,
        transform: [{ rotate: '-6deg' }],
    },
    wave: {
        position: 'absolute',
        left: -40,
        right: -40,
        bottom: -120,
        height: 360,
        borderTopLeftRadius: 200,
        borderTopRightRadius: 200,
        opacity: 0.85,
        transform: [{ rotate: '-2deg' }],
    },
    beginBtn: {
        position: 'absolute',
        bottom: 72,
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
        paddingHorizontal: 26,
        height: 56,
        borderRadius: 18,
        backgroundColor: '#FFFFFF',
        shadowOpacity: 0.14,
        shadowOffset: { width: 0, height: 10 },
        shadowRadius: 18,
        elevation: 3,
        zIndex: 1,
    },
    beginText: {
        fontSize: 16,
        fontWeight: '800',
        letterSpacing: 0.4,
    },
});

export default styles;
